baseURL = "glovelet.github.io"			# Site's URL
title = "Glovlet - Advance Tracking Gloves"
theme = "manis"
copyright = "&copy; 2017 UTA PiedPiper"	
pluralizeListTitles = false
paginate = 10					
canonifyURL = true
disqusShortname = "glovelet"                        # Your disqus shortname

[taxonomies]
	tag = "tags"


[params]
	debugCSS = false                        # If false, use minified CSS (ui.min.css)
	disqusSections = ["blog"]               # list of section support disqus comments
	# Site meta description
	description = "Team 1"
	tagline = "UTA- PiedPiper"   # Site's Tagline (Subtitle or Keyword)
	themeAttrib = false                      # If true give attribution to this theme

	# 404 Configuration
	head404 = "Sorry, I can find what you want."
	sub404 = "Back to <a href='/'>Home</a>."

	colorTheme = "#ff8181"                  # Color of your website
	latestCount = 3                         # Maximum number of item in Latest Posts or Works
	faviconImg = ""                         # Path to site's favicon image
	dateFmt = "Jan 02, 2006"                # Date format in item list

	# Code Highlighting (HighlightJS)
	highlightJs = true
	highlightJsLanguages = [ "go" ]
	highlightJsStyle = "ocean"

	# Social Links
	email = "thearnavgarg@gmail.com"
	github = ""


# Language Configuration
defaultContentLanguage = "en"
